# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink: "/:title"
relative_permalinks: true

highlighter: pygments

timezone: Europe/Helsinki

# Tagging settings
tag_title_prefix:   "Posts tagged #"
tag_title_suffix:   ""

# Facebook settings
fb_admins:          606660677
avatar:             "/public/images/me_hires.png"
locale:             en_US

# Image settings
image_base:          /public/images/

#fb_appid:           337414769782635

# Setup
title:               Vitaly Repin
tagline:             Sapere aude!
url:                 "http://vrepin.org"
paginate:            4
baseurl:             "/vr"

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Vitaly Repin
  url:               https://twitter.com/vitalyrepin
  email:             vitaly_repin@fsfe.org

# Custom vars
version:             1.0.0
github:
  repo:              https://github.com/vitalyrepin/vrepinblog

# Google sitemap generation
gems:
  - jekyll-sitemap

pages_list:
  About: '/vr/about/'
  Hobby projects: '/vr/hobbies/'
  Tags: '/vr/tags/'
  Feed: '/vr/atom.xml'

